Traceback (most recent call last):
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import shenfun as sf

ue = 1 / (1+16*x**2)
N = 20
V = sf.FunctionSpace(N+1, 'Legendre', domain=(-1, 1))
v = sf.TestFunction(V)
uh = (2*np.arange(N)+1)/2*sf.inner(ue, v, assemble='exact')
#uh = sf.project(ue, V) # or just this
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[16], line 7[0m
[1;32m      5[0m V [38;5;241m=[39m sf[38;5;241m.[39mFunctionSpace(N[38;5;241m+[39m[38;5;241m1[39m, [38;5;124m'[39m[38;5;124mLegendre[39m[38;5;124m'[39m, domain[38;5;241m=[39m([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m1[39m))
[1;32m      6[0m v [38;5;241m=[39m sf[38;5;241m.[39mTestFunction(V)
[0;32m----> 7[0m uh [38;5;241m=[39m [43m([49m[38;5;241;43m2[39;49m[38;5;241;43m*[39;49m[43mnp[49m[38;5;241;43m.[39;49m[43marange[49m[43m([49m[43mN[49m[43m)[49m[38;5;241;43m+[39;49m[38;5;241;43m1[39;49m[43m)[49m[38;5;241;43m/[39;49m[38;5;241;43m2[39;49m[38;5;241;43m*[39;49m[43msf[49m[38;5;241;43m.[39;49m[43minner[49m[43m([49m[43mue[49m[43m,[49m[43m [49m[43mv[49m[43m,[49m[43m [49m[43massemble[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mexact[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      8[0m [38;5;66;03m#uh = sf.project(ue, V) # or just this[39;00m

[0;31mValueError[0m: operands could not be broadcast together with shapes (20,) (21,) 

